### ISSUE TITLE
phase 1 task list

### ISSUE THREAD

**Issue by WillaFan** [WillaFan/aws#3]
arrive at aws each work day, perform following suggested tasks

- [ ] Check health (such as ADMIN user groups, users, permissions;
- [ ] [Amazon OpenSearch Service](https://ap-southeast-1.console.aws.amazon.com/esv3/home?region=ap-southeast-1#/opensearch);
- [ ] All account environments configuration on cloud9;
- [ ] Figure out ambiguity in EC2 environment, EC2 instance and server)
  
- [ ] to be finished [Step 2: Upload data for indexing](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/gsgupload-data.html)
